export {default as HomeView} from './Homeview.vue'
export {default as Login} from './Login.vue'
export {default as Register} from './Register.vue'
export {default as ArticleDetail} from './ArticleDetailview.vue'
export {default as CreateArticle} from './CreateArticleView.vue'